### ISSUE TITLE
Export to PNG or JPEG is pink in Firefox on Ubuntu

### ISSUE THREAD

**Issue by maivincent** [YunoHost-Apps/diagramsnet_ynh#11]
Hi,

I am using diagrams.net in Firefox 85.0.1 (64-bit) - Mozilla Firefox for Ubuntu canonical - 1.0.
When exporting in PNG or JPEG, the resulting file has a strong pink color (see images) whereas it should not. This happens with or without the "Transparent background" option selected.

This does not happen on Chromium Version 88.0.4324.182 (Official Build) snap (64-bit) for Ubuntu, where the same file is exported correctly.

Firefox export (pink):
![Untitled Diagram(4)](https://user-images.githubusercontent.com/11266099/108558333-c428d200-72c7-11eb-8150-4b6a7ec16dab.png)

Chromium export (correct):
![Untitled Diagram (2)](https://user-images.githubusercontent.com/11266099/108558385-d4d94800-72c7-11eb-807a-f3d95a77d908.png)

**Comment by Gofannon** [comment]
Hello,

Could you try with the latest version fro YunoHost? The App was late behind the Diagram project
