### ISSUE TITLE
Fails to upgrade to v24.0.4, checksum don't match

### ISSUE THREAD

**Issue by sereinity** [YunoHost-Apps/diagramsnet_ynh#198]
### Describe the bug

Can't upgrade from `v24.0.2~ynh1` to `v24.0.4~ynh1` due to bad checksum match.

### Context

- Hardware: RaspberryPi4
- YunoHost version: 11.2.10.3
- I have access to my server: SSH | webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: v24.0.4~ynh1
- If upgrading, current package version: v24.0.2~ynh1

### Steps to reproduce

(As the checksum isn't valid, a simple install is sufficient to reach the error).

- Go to Applications
- Click on Install
- Search for Diagrams.net
- Allow admins to access the app
- Change path to not conflict to an existing install
- Click on install
- An error occurs on checksum validation

### Expected behavior

The checksum should match.

### Logs

https://paste.yunohost.org/raw/huwitucuvo

**Comment by ericgaspar** [comment]
should be fixed
